apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-shared-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

