apiVersion: v1
kind: Pod
metadata:
  name: ebs-writer
  namespace: default
spec:
  containers:
    - name: app
      image: public.ecr.aws/docker/library/alpine:3
      command: ["/bin/sh","-c"]
      args:
        - |
          while true; do
            sleep 3600;
          done
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ebs-test-pvc

